services:
  backend:
    build:
      context: .
      dockerfile: back-end/Dockerfile
    image: softy-pinko-back-end:task4
    ports:
      - "5252:5252"

  frontend:
    build:
      context: .
      dockerfile: front-end/Dockerfile
    image: softy-pinko-front-end:task4
    ports:
      - "9000:9000"
    depends_on:
      - backend

  
